CREATE TABLE `shopee_ads_data` (
	`id` int AUTO_INCREMENT NOT NULL,
	`uploadId` int NOT NULL,
	`adNumber` int,
	`adName` text,
	`status` varchar(50),
	`adType` varchar(100),
	`productId` varchar(50),
	`bidMethod` text,
	`placement` varchar(50),
	`keyword` text,
	`combinationType` varchar(50),
	`startDate` varchar(50),
	`endDate` varchar(50),
	`impressions` int DEFAULT 0,
	`clicks` int DEFAULT 0,
	`ctr` double DEFAULT 0,
	`conversions` int DEFAULT 0,
	`directConversions` int DEFAULT 0,
	`conversionRate` double DEFAULT 0,
	`directConversionRate` double DEFAULT 0,
	`costPerConversion` double DEFAULT 0,
	`costPerDirectConversion` double DEFAULT 0,
	`itemsSold` int DEFAULT 0,
	`directItemsSold` int DEFAULT 0,
	`gmv` double DEFAULT 0,
	`directRevenue` double DEFAULT 0,
	`spend` double DEFAULT 0,
	`roas` double DEFAULT 0,
	`directRoas` double DEFAULT 0,
	`acos` double DEFAULT 0,
	`directAcos` double DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `shopee_ads_data_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `shopee_ads_uploads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`filename` varchar(255) NOT NULL,
	`fileKey` varchar(512) NOT NULL,
	`fileUrl` text NOT NULL,
	`fileSize` bigint NOT NULL,
	`totalAds` int NOT NULL DEFAULT 0,
	`periodStart` varchar(10),
	`periodEnd` varchar(10),
	`uploadedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `shopee_ads_uploads_id` PRIMARY KEY(`id`)
);
